# Generated by Django 6.0.3 on 2026-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('plan_interes', models.CharField(choices=[('titanium', 'Titanium'), ('vip_platinum', 'VIP Platinum'), ('informacion', 'Solo información')], default='informacion', max_length=20)),
                ('origen', models.CharField(default='viaja-con-favi', max_length=50)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
