# Generated by Django 6.0.3 on 2026-03-31 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('codigo_pais', models.CharField(max_length=3)),
                ('bandera_emoji', models.CharField(max_length=10)),
                ('imagen', models.URLField()),
                ('numero_resorts', models.IntegerField()),
                ('continente', models.CharField(choices=[('america_norte', 'América del Norte'), ('america_central', 'América Central'), ('america_sur', 'América del Sur'), ('europa', 'Europa'), ('asia', 'Asia'), ('africa', 'Africa'), ('oceania', 'Oceanía')], max_length=20)),
                ('comida', models.CharField(max_length=100)),
                ('transfers', models.CharField(max_length=100)),
                ('extras', models.JSONField(default=list)),
                ('precio_desde', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['orden', 'pais'],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('duracion_dias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('incluye', models.JSONField(default=list)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='destinos.destino')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['-destacado', 'precio'],
            },
        ),
    ]
