# Generated by Django 6.0.3 on 2026-04-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_blogempresa_ofertaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/'),
        ),
    ]
