# Generated by Django 6.0.3 on 2026-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('titanium', 'Titanium'), ('vip_platinum', 'VIP Platinum')], max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida'), ('pendiente', 'Pendiente de pago')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_renovacion', models.DateField(blank=True, null=True)),
                ('inversion_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mensualidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('puntos_inicio', models.IntegerField(default=0)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('puntos_canjeados', models.IntegerField(default=0)),
                ('num_referidos_activos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('membresia_activa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Referido',
                'verbose_name_plural': 'Referidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
