# Generated by Django 6.0.3 on 2026-03-31 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='membresias.membresia'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referido_desde', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_dados', to=settings.AUTH_USER_MODEL),
        ),
    ]
