# Generated by Django 6.0.3 on 2026-03-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('titanium', 'Titanium'), ('vip_platinum', 'VIP Platinum')], max_length=50, unique=True)),
                ('subtitulo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('mensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_inicio', models.IntegerField(default=0)),
                ('puntos_mensuales', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('caracteristicas', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden'],
            },
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='inversion_inicial',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='mensualidad',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='puntos_inicio',
        ),
        migrations.AlterField(
            model_name='membresia',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membresias.plan'),
        ),
    ]
